apiVersion: batch/v1
kind: Job
metadata:
  name: hello-moto-err
spec:
  template:
    spec:
      containers:
      - name: hello-moto-err
        image: ubuntu
        command: ["echo",  "syntaxError]
      restartPolicy: Never
  backoffLimit: 4
