apiVersion: batch/v1
kind: Job
metadata:
  name: python-err
spec:
  template:
    spec:
      containers:
      - name: python-err
        image: ubuntu
        command: ["python",  "/scriptThatDoesntExist.py"]
      restartPolicy: Never
  backoffLimit: 4
